# Generated by Django 6.0.5 on 2026-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.BigAutoField(db_column='trainer_id', primary_key=True, serialize=False)),
                ('trainer_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.PROTECT, related_name='trainers', to='programs.gender')),
            ],
            options={
                'db_table': 'trainers',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_id', models.BigAutoField(db_column='certification_id', primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=150)),
                ('issuing_authority', models.CharField(blank=True, max_length=150)),
                ('certificate_no', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='trainers.trainer')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-issue_date', 'certification_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTrainer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization for this program', max_length=200)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='programs.program')),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='trainers.trainer')),
            ],
            options={
                'db_table': 'program_trainers',
                'ordering': ['program', 'trainer'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'program'), name='uniq_trainer_program')],
            },
        ),
        migrations.CreateModel(
            name='CourseTrainer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='programs.course')),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='trainers.trainer')),
            ],
            options={
                'db_table': 'course_trainers',
                'ordering': ['course', 'trainer'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'course'), name='uniq_trainer_course')],
            },
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_id', models.PositiveIntegerField()),
                ('proficiency_level', models.CharField(max_length=50)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='trainers.trainer')),
            ],
            options={
                'db_table': 'trainer_skills',
                'ordering': ['trainer_id', 'skill_id'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'skill_id'), name='uniq_trainer_skill')],
            },
        ),
    ]
