# Generated by Django 6.0.5 on 2026-05-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.BigAutoField(db_column='certificate_id', primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=80, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('verification_code', models.CharField(max_length=120, unique=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='batches.enrollment')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issue_date', 'certificate_no'],
            },
        ),
    ]
