# Generated by Django 6.0.5 on 2026-05-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(db_column='student_id', primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.city')),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.gender')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('guardian_id', models.BigAutoField(db_column='guardian_id', primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=60)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'db_table': 'student_guardians',
                'ordering': ['guardian_name'],
            },
        ),
    ]
