# Generated by Django 4.2.9 on 2026-05-29 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureProposal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("program_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("institute_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pravaah_future_proposal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GateZeroForm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "is_training_room_available",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                (
                    "is_hostel_facility_available",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                (
                    "is_trainer_available",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                (
                    "is_proposal_financially_feasible",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_zero",
                        to="pravaah.futureproposal",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pravaah_gate_zero",
            },
        ),
        migrations.CreateModel(
            name="GateApprovalForm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name_of_client",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mt_course_registration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_participants", models.IntegerField(default=0)),
                (
                    "training_type_online_offline",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("training_need_type", models.TextField(blank=True, null=True)),
                ("training_need_content", models.TextField(blank=True, null=True)),
                ("prep_sta_infra", models.TextField(blank=True, null=True)),
                ("prep_consumables", models.TextField(blank=True, null=True)),
                ("prep_ctea_infra", models.TextField(blank=True, null=True)),
                ("prep_mt_availability", models.TextField(blank=True, null=True)),
                ("prep_material", models.TextField(blank=True, null=True)),
                ("prep_material_ppt", models.TextField(blank=True, null=True)),
                ("prep_feedback", models.TextField(blank=True, null=True)),
                ("session_plan_availability", models.TextField(blank=True, null=True)),
                ("value_addition", models.TextField(blank=True, null=True)),
                ("assessment_formative", models.TextField(blank=True, null=True)),
                ("assessment_summative", models.TextField(blank=True, null=True)),
                ("assessment_certification", models.TextField(blank=True, null=True)),
                ("assessment_assessors", models.TextField(blank=True, null=True)),
                ("invoicing_documents", models.TextField(blank=True, null=True)),
                ("fees_standard_deviations", models.TextField(blank=True, null=True)),
                ("challenges_mitigation", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            (
                                "Pending Marketing Approval",
                                "Pending Marketing Approval",
                            ),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending Marketing Approval",
                        max_length=50,
                    ),
                ),
                ("marketing_remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_approval",
                        to="pravaah.futureproposal",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_gate_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_gate_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pravaah_gate_approval",
            },
        ),
    ]
