# Generated by Django 6.0.5 on 2026-05-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='block',
            table='blocks',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
        migrations.AlterModelTable(
            name='feepayment',
            table='fee_payments',
        ),
        migrations.AlterModelTable(
            name='floor',
            table='floors',
        ),
        migrations.AlterModelTable(
            name='hostel',
            table='hostels',
        ),
        migrations.AlterModelTable(
            name='maintenancerequest',
            table='maintenance_requests',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roomallocation',
            table='room_allocations',
        ),
        migrations.AlterModelTable(
            name='roomtransfer',
            table='room_transfers',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='visitors',
        ),
    ]
