# Generated by Django 6.0.5 on 2026-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmgmt', '0005_roomallocation_actual_checkout_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_email',
            field=models.EmailField(blank=True, default='', max_length=150),
        ),
    ]
