# Generated by Django 6.0.5 on 2026-05-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='student',
                    name='city',
                ),
                migrations.AddField(
                    model_name='student',
                    name='academic_year_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='student',
                    name='course_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='student',
                    name='user_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='email',
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='first_name',
                    field=models.CharField(max_length=100),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='gender',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='join_date',
                    field=models.DateField(blank=True, db_column='created_at', null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='last_name',
                    field=models.CharField(blank=True, max_length=150, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='mobile',
                    field=models.CharField(blank=True, max_length=15, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='status',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='student_code',
                    field=models.CharField(blank=True, db_column='admission_no', max_length=64, unique=True),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='student_id',
                    field=models.BigAutoField(db_column='participant_id', primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='email',
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='guardian_name',
                    field=models.CharField(max_length=200),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='mobile',
                    field=models.CharField(blank=True, max_length=15, null=True),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='occupation',
                    field=models.TextField(blank=True, db_column='address', null=True),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='relation',
                    field=models.CharField(blank=True, db_column='relationship', max_length=50, null=True),
                ),
                migrations.AlterField(
                    model_name='studentguardian',
                    name='student',
                    field=models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student'),
                ),
                migrations.AlterModelTable(
                    name='student',
                    table='participants',
                ),
                migrations.AlterModelTable(
                    name='studentguardian',
                    table='participant_guardians',
                ),
            ],
        ),
    ]
