# Generated by Django 6.0.5 on 2026-05-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_course_table'),
        ('students', '0002_remove_student_city_student_academic_year_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='student',
                    name='course_id',
                ),
                migrations.AddField(
                    model_name='student',
                    name='course',
                    field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='programs.course'),
                ),
            ],
        ),
    ]
