# Generated by Django 6.0.5 on 2026-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(db_column='attendance_id', primary_key=True, serialize=False)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('attendance_photo', models.ImageField(blank=True, db_column='attendance_photo', null=True, upload_to='attendance/')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='batches.enrollment')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='batches.session')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-marked_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'session'), name='uniq_enrollment_session_attendance')],
            },
        ),
    ]
