# Generated by Django 6.0.5 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_photo',
            field=models.ImageField(blank=True, db_column='attendance_photo', null=True, upload_to='attendance/'),
        ),
    ]
