# Generated by Django 6.0.5 on 2026-05-29 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.BigAutoField(db_column='academic_year_id', primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=20, unique=True)),
                ('city_name', models.CharField(max_length=120)),
                ('state_name', models.CharField(blank=True, max_length=120)),
                ('country_name', models.CharField(default='India', max_length=120)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=150)),
                ('course_image', models.ImageField(blank=True, db_column='course_image', null=True, upload_to='courses/')),
                ('description', models.TextField(blank=True)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('level', models.CharField(default='Beginner', max_length=30)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'courses_tcm',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20, unique=True)),
                ('category_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'course_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.BigAutoField(db_column='gender_id', primary_key=True, serialize=False)),
                ('gender_code', models.CharField(max_length=20, unique=True)),
                ('gender_name', models.CharField(max_length=40)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'genders',
                'ordering': ['gender_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.BigAutoField(db_column='room_type_id', primary_key=True, serialize=False)),
                ('room_type_code', models.CharField(max_length=20, unique=True)),
                ('room_type_name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['room_type_name'],
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_master_id', models.BigAutoField(db_column='status_master_id', primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=80)),
                ('status_code', models.CharField(max_length=40)),
                ('status_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'status_master',
                'ordering': ['entity_name', 'status_name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.BigAutoField(db_column='module_id', primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=150)),
                ('module_image', models.ImageField(blank=True, db_column='module_image', null=True, upload_to='modules/')),
                ('description', models.TextField(blank=True)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='programs.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['sequence_no', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(db_column='material_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('file_type', models.CharField(max_length=40)),
                ('file_url', models.FileField(db_column='file_url', upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='programs.module')),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.BigAutoField(db_column='program_id', primary_key=True, serialize=False)),
                ('program_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('program_name', models.CharField(max_length=150)),
                ('program_image', models.ImageField(blank=True, db_column='program_image', null=True, upload_to='programs/')),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.coursecategory')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_program_links', to='programs.course')),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='programs.program')),
            ],
            options={
                'db_table': 'program_courses',
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'module_name'), name='uniq_course_module'),
        ),
        migrations.AddConstraint(
            model_name='programcourse',
            constraint=models.UniqueConstraint(fields=('program', 'course'), name='uniq_program_course'),
        ),
    ]
