# Generated by Django 6.0.5 on 2026-05-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='course',
                    table='courses',
                ),
            ],
        ),
    ]
