# Generated by Django 5.2.14 on 2026-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('duration_years', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='student_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True, unique=True)),
                ('admission_no', models.CharField(db_column='admission_no', max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('academic_year_id', models.CharField(blank=True, db_column='academic_year_id', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='participantmgmt.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('guardian_id', models.AutoField(db_column='guardian_id', primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='participantmgmt.student')),
            ],
            options={
                'db_table': 'student_guardians',
            },
        ),
    ]
