# Generated by Django 6.0.5 on 2026-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('students', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.BigAutoField(db_column='batch_id', primary_key=True, serialize=False)),
                ('batch_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('batch_name', models.CharField(max_length=150)),
                ('client_name', models.CharField(blank=True, default='', max_length=80)),
                ('subject_short_name', models.CharField(blank=True, default='', max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(default='Offline', max_length=30)),
                ('status', models.CharField(default='Planned', max_length=20)),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='programs.program')),
                ('trainer', models.ForeignKey(blank=True, db_column='trainer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='trainers.trainer')),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['-start_date', 'batch_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.BigAutoField(db_column='session_id', primary_key=True, serialize=False)),
                ('session_topic', models.CharField(max_length=200)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batches.batch')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programs.course')),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='trainers.trainer')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(db_column='enrollment_id', primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='batches.batch')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date', 'enrollment_id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'student'), name='uniq_batch_student')],
            },
        ),
    ]
