# Generated by Django 6.0.5 on 2026-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.BigAutoField(db_column='assessment_id', primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=150)),
                ('assessment_type', models.CharField(max_length=60)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='programs.course')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at', 'assessment_name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('result_id', models.BigAutoField(db_column='result_id', primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment')),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='batches.enrollment')),
            ],
            options={
                'db_table': 'assessment_results',
                'ordering': ['-submitted_at', 'result_id'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'assessment'), name='uniq_enrollment_assessment')],
            },
        ),
    ]
