# Generated by Django 6.0.5 on 2026-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmgmt', '0003_waitinglist_update_roomallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='reason',
            field=models.TextField(blank=True, default='Drag & Drop Transfer'),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='student_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
