# Generated by Django 6.0.5 on 2026-05-29 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmgmt', '0004_alter_roomallocation_student_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_id',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin remarks / action taken', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Name of staff member handling this', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='actual_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp recorded by security when occupant physically checks out.', null=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed the checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_email',
            field=models.EmailField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('wifi', 'Wi-Fi / Network'), ('cleaning', 'Cleaning'), ('furniture', 'Furniture'), ('pest', 'Pest Control'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='hostelmgmt.room'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requested_by',
            field=models.CharField(default='System', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hostelmgmt.room'),
        ),
        migrations.AlterModelTable(
            name='complaint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='maintenancerequest',
            table=None,
        ),
    ]
