# Generated by Django 6.0.5 on 2026-05-29 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmgmt', '0004_alter_roomallocation_student_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallocation',
            name='actual_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp recorded by security when occupant physically checks out.', null=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed the checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_checkouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
