# Generated by Django 6.0.5 on 2026-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, db_column='course_image', null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='module',
            name='module_image',
            field=models.ImageField(blank=True, db_column='module_image', null=True, upload_to='modules/'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, db_column='program_image', null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
